name: docker-build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: evmos

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write 
      packages: write 
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: up a level
        run: cd .. && pwd
      - name: Clone evmos repo
        uses: actions/checkout@v2
        with:
          repository: jbowen93/evmos
          path: evmos
      - name: Clone ethermint repo
        uses: actions/checkout@v2
        with:
          repository: celestiaorg/ethermint
          path: ethermint
      - name: Clone ephemeral-cluster repo
        uses: actions/checkout@v2
        with:
          repository: celestiaorg/ephemeral-cluster
          path: ephemeral-cluster
          ref: jbowen93/evmos
      - name: Move Stuff
        run: |
          mv evmos ..
          mv ethermint ..
          mv ephemeral-cluster ..
          cd .. && tree
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=optimint-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          pwd
          ./build-image.sh ${{ steps.meta.outputs.tags[0] }}